# Generated by Django 2.2.5 on 2019-09-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruletApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rulets',
        ),
        migrations.CreateModel(
            name='RuletChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulet_choices', to='ruletApp.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulet_choices', to='ruletApp.Employee')),
                ('rulet_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulet_choices', to='ruletApp.RuletSession')),
            ],
        ),
    ]
