# Generated by Django 2.2.5 on 2019-09-20 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruletApp', '0002_auto_20190920_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruletsession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
