# Generated by Django 2.2.5 on 2019-09-18 07:22

from django.db import migrations, models
import ruletApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ruletApp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to=ruletApp.models.get_employee_folder_path),
        ),
    ]
