# Generated by Django 2.2.5 on 2019-09-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruletApp', '0003_ruletsession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruletsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
